### ISSUE TITLE
python 2 support?

### ISSUE THREAD

**Issue by Sispheor** [milaq/rpi-rf#12]
As Python 2.7 is still the default interpreter on a Rpi..

**Comment by Landrash** [comment]
Same argument Python3 is available in the package repository shipped with Raspbian.

**Comment by Sispheor** [comment]
Absolutely. But the native interpreter is still 2.7.
Anyway, do you mind if I PR a python 2 support?
I haven't read the whole code yet but it seems possible, right?

**Comment by milaq** [comment]
Sorry, no support for python 2. I'd need to have an eye on two different codebases then.

**Comment by vchlum** [comment]
@Sispheor It works well with just small changes. See https://github.com/vchlum/rpi-rf/tree/python2
