### ISSUE TITLE
function's arguments mismatch

### ISSUE THREAD

**Issue by Yossig** [milaq/rpi-rf#31]
it happens when installing via 'pip3 install rpi-rf',

in module rpi_rf.py, function tx_code takes only 3 arguments. (different from the latest code version here)
while rpi-rf_send.py sends to the function 4 arguments (the arg.length does not exist in rpi_rf.py if installing with pip3 install rpi-rf)

**Comment by giuseppeg88** [comment]
I think this is due to the fact that the latest version on pypi.org is 0.9.6 of Apr 25, 2016 (and therefore not updated).

**Comment by Yossig** [comment]
why don't you update to latest version?

**Comment by giuseppeg88** [comment]
Yes, considering that several changes have been made it would be good to have a new release.
@milaq, can you help us? ;-)

**Comment by milaq** [comment]
I am pretty busy atm but I will tag a new release soon™, hopefully until the end of the month.

Until then, please use this (older) version of the example script:
https://github.com/milaq/rpi-rf/blob/918e2bf86a828947354ca19762b78d1795df8788/scripts/rpi-rf_send

**Comment by milaq** [comment]
Sorry for the delay, totally forgot about this.

I just tagged a new release. See https://pypi.org/project/rpi-rf/0.9.7/
