### ISSUE TITLE
Why no voltage divider on wiring diagram?

### ISSUE THREAD

**Issue by bulletmark** [milaq/rpi-rf#36]
Everywhere I read that if you power these RF Rx devices with 5V then it is critical to divide the voltage down on the Rx data pin to 3.3V before connecting it to a RPi GPIO input pin otherwise you risk damaging the RPi.

However, the wiring diagram on the main README does not show this? The Rx data pin (potentially at 5V)  is connected directly to the GPIO input (max should be 3.3V) so presumably at risk of damaging it?

**Comment by milaq** [comment]
I used those modules for years connected directly to the GPIO header.
I didn't measure the DATA voltage, but it didn't pose any problem until now and never heard of anyone damaging his Pi with it.

If unsure, you can put a AMS1117 between the 5V lane and the modules' input. They are usually found very cheap on Alix, Banggood or Gearbest.
